"""AI Project Decomposition Engine.

Given a natural-language command, produce a structured plan:
  epics -> stories -> tasks -> subtasks, with disciplines, estimates,
  suggested owners and dependencies.

If OPENAI_API_KEY is configured, the plan is generated by the LLM with a
strict JSON contract. Otherwise a deterministic keyword-driven template
engine produces a credible plan so the platform works fully offline.
"""
import json
import httpx
from .. import config

DISCIPLINES = ["business", "design", "development", "qa", "documentation",
               "deployment", "marketing", "manufacturing", "sales", "support"]

SYSTEM_PROMPT = """You are the Legendium OS planning engine, acting as a virtual COO
for Legendium (VR/XR + Robotics + Operations).

Team:
- joseph (admin, oversees everything)
- amal (VR/XR lead) -> noel (3D assets), vishnu (website/UI-UX), krishnaprasad (backend/integrations/AI)
- anson (Robotics lead) -> vysakh (testing/assembly/QC/manufacturing)
- Operations work (Amazon, Flipkart, logistics, procurement, packaging) is owned by joseph.

Products: NanoSpark, Otto, Ninja, Megapath, Project K (robots); Legendium Game chapters,
website, asset pipeline, animations (VR/XR).

Given the user command, respond with ONLY valid JSON:
{
 "summary": "...",
 "department": "vrxr|robotics|operations",
 "project": "project name",
 "epics": [
  {"title": "...", "description": "...", "discipline": "...",
   "stories": [
    {"title": "...", "description": "...", "discipline": "...", "owner": "username",
     "estimate_hours": 8,
     "tasks": [
      {"title": "...", "discipline": "...", "owner": "username", "estimate_hours": 4,
       "subtasks": [{"title": "...", "owner": "username", "estimate_hours": 2}]}
     ]}
   ]}
 ],
 "dependencies": [{"blocker": "exact task title", "blocked": "exact task title"}],
 "milestones": [{"name": "...", "offset_days": 14}]
}
Disciplines must be one of: business, design, development, qa, documentation,
deployment, marketing, manufacturing, sales, support.
Owners must be usernames above, matched to skills. Be specific and realistic."""


async def decompose(command: str, context: str = "") -> dict:
    if config.OPENAI_API_KEY:
        try:
            return await _decompose_llm(command, context)
        except Exception as e:  # graceful fallback
            plan = _decompose_local(command)
            plan["engine"] = f"local-fallback ({type(e).__name__})"
            return plan
    plan = _decompose_local(command)
    plan["engine"] = "local"
    return plan


async def _decompose_llm(command: str, context: str) -> dict:
    user_msg = command if not context else f"{command}\n\nRelevant knowledge base context:\n{context}"
    async with httpx.AsyncClient(timeout=90) as client:
        r = await client.post(
            f"{config.OPENAI_BASE_URL}/chat/completions",
            headers={"Authorization": f"Bearer {config.OPENAI_API_KEY}"},
            json={
                "model": config.OPENAI_MODEL,
                "response_format": {"type": "json_object"},
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
            },
        )
        r.raise_for_status()
        plan = json.loads(r.json()["choices"][0]["message"]["content"])
        plan["engine"] = config.OPENAI_MODEL
        return plan


# ---------------------------------------------------------------- local engine

def _t(title, discipline, owner, est, subtasks=None):
    return {"title": title, "discipline": discipline, "owner": owner,
            "estimate_hours": est, "subtasks": subtasks or []}


def _decompose_local(command: str) -> dict:
    c = command.lower()
    robotics = any(k in c for k in ["nano", "otto", "ninja", "megapath", "project k",
                                    "pcb", "robot", "manufactur", "assembly"])
    ops = any(k in c for k in ["flipkart", "amazon", "listing", "logistics",
                               "procure", "packag", "marketing campaign"])
    chapter = "chapter" in c
    website = "website" in c or "web release" in c

    if chapter or (not robotics and not ops):
        return _plan_chapter(command, include_listing=("flipkart" in c or "amazon" in c),
                             include_site=website, include_nano=("nano" in c))
    if robotics:
        return _plan_robot_launch(command)
    return _plan_listing(command)


def _plan_chapter(command, include_listing=False, include_site=False, include_nano=False):
    epics = [{
        "title": "Chapter content production",
        "description": "Narrative, environment and asset production for the new chapter.",
        "discipline": "design",
        "stories": [
            {"title": "Narrative and level design", "discipline": "design",
             "owner": "amal", "estimate_hours": 16, "description": "Story beats, level flow, gameplay loops.",
             "tasks": [
                 _t("Write chapter script and beats", "design", "amal", 8),
                 _t("Blockout level layout", "design", "noel", 10,
                    [{"title": "Greybox environment", "owner": "noel", "estimate_hours": 6},
                     {"title": "Playtest blockout", "owner": "amal", "estimate_hours": 4}]),
             ]},
            {"title": "3D asset pipeline", "discipline": "design",
             "owner": "noel", "estimate_hours": 40, "description": "Models, textures, animations.",
             "tasks": [
                 _t("Model hero assets", "design", "noel", 16),
                 _t("Texture and material pass", "design", "noel", 12),
                 _t("Rig and animate characters", "design", "noel", 12),
             ]},
        ],
    }, {
        "title": "Chapter engineering",
        "description": "Gameplay code, integrations and backend services.",
        "discipline": "development",
        "stories": [
            {"title": "Gameplay systems", "discipline": "development",
             "owner": "krishnaprasad", "estimate_hours": 32, "description": "Mechanics, triggers, save state.",
             "tasks": [
                 _t("Implement chapter mechanics", "development", "krishnaprasad", 16),
                 _t("Hook telemetry and analytics", "development", "krishnaprasad", 8),
                 _t("Performance optimization pass", "development", "krishnaprasad", 8),
             ]},
            {"title": "QA and release", "discipline": "qa",
             "owner": "vysakh", "estimate_hours": 20, "description": "Test plan, regression, release checklist.",
             "tasks": [
                 _t("Write chapter test plan", "qa", "amal", 4),
                 _t("Execute regression suite", "qa", "vysakh", 10),
                 _t("Release build and deploy", "deployment", "krishnaprasad", 6),
             ]},
        ],
    }]
    deps = [
        {"blocker": "Blockout level layout", "blocked": "Model hero assets"},
        {"blocker": "Implement chapter mechanics", "blocked": "Execute regression suite"},
        {"blocker": "Execute regression suite", "blocked": "Release build and deploy"},
    ]
    if include_nano:
        epics.append({
            "title": "NanoSpark hardware integration",
            "description": "Bridge chapter gameplay with NanoSpark robot.",
            "discipline": "development",
            "stories": [{
                "title": "Nano <-> game bridge", "discipline": "development",
                "owner": "anson", "estimate_hours": 24,
                "description": "Firmware hooks, BLE protocol, in-game pairing.",
                "tasks": [
                    _t("Define BLE command protocol", "development", "anson", 6),
                    _t("Firmware event hooks", "development", "anson", 10),
                    _t("In-game pairing flow", "development", "krishnaprasad", 8),
                    _t("Integration test on 5 units", "qa", "vysakh", 6),
                ]}],
        })
        deps.append({"blocker": "Firmware event hooks", "blocked": "In-game pairing flow"})
        deps.append({"blocker": "In-game pairing flow", "blocked": "Integration test on 5 units"})
    if include_site:
        epics.append({
            "title": "Website release",
            "description": "Landing page update and chapter announcement.",
            "discipline": "marketing",
            "stories": [{
                "title": "Chapter landing page", "discipline": "design",
                "owner": "vishnu", "estimate_hours": 20,
                "description": "Hero section, trailer embed, SEO.",
                "tasks": [
                    _t("Design landing page", "design", "vishnu", 8),
                    _t("Build and deploy page", "development", "vishnu", 8),
                    _t("Announcement content", "marketing", "joseph", 4),
                ]}],
        })
        deps.append({"blocker": "Design landing page", "blocked": "Build and deploy page"})
    if include_listing:
        epics.append(_listing_epic())
        deps.append({"blocker": "Release build and deploy", "blocked": "Publish marketplace listing"})
    return {
        "summary": f"Decomposed: {command}",
        "department": "vrxr", "project": "Chapter Development",
        "epics": epics, "dependencies": deps,
        "milestones": [
            {"name": "Content lock", "offset_days": 14},
            {"name": "QA complete", "offset_days": 24},
            {"name": "Public release", "offset_days": 30},
        ],
    }


def _listing_epic():
    return {
        "title": "Marketplace listing",
        "description": "Flipkart / Amazon listing creation and launch.",
        "discipline": "sales",
        "stories": [{
            "title": "Listing production", "discipline": "marketing",
            "owner": "joseph", "estimate_hours": 16,
            "description": "Copy, imagery, A+ content, pricing, logistics setup.",
            "tasks": [
                _t("Product photography and renders", "marketing", "noel", 6),
                _t("Listing copy and keywords", "marketing", "joseph", 4),
                _t("Pricing and margin sheet", "business", "joseph", 3),
                _t("Publish marketplace listing", "sales", "joseph", 3),
            ]}],
    }


def _plan_robot_launch(command):
    return {
        "summary": f"Decomposed: {command}",
        "department": "robotics", "project": "NanoSpark",
        "epics": [
            {"title": "Hardware production readiness", "description": "PCB, enclosure, BOM, vendors.",
             "discipline": "manufacturing",
             "stories": [
                 {"title": "PCB production pipeline", "discipline": "manufacturing",
                  "owner": "anson", "estimate_hours": 30, "description": "Final rev, DFM, vendor PO.",
                  "tasks": [
                      _t("Final PCB revision and DFM check", "development", "anson", 10),
                      _t("Vendor quotes and PO", "business", "joseph", 6),
                      _t("Pilot batch of 50 boards", "manufacturing", "anson", 8,
                         [{"title": "Incoming QC on pilot batch", "owner": "vysakh", "estimate_hours": 6}]),
                  ]},
                 {"title": "Enclosure and packaging", "discipline": "manufacturing",
                  "owner": "anson", "estimate_hours": 24, "description": "CAD freeze, molds, retail packaging.",
                  "tasks": [
                      _t("Freeze enclosure CAD", "design", "anson", 8),
                      _t("Packaging dieline and print", "design", "joseph", 8),
                      _t("Assembly SOP document", "documentation", "vysakh", 8),
                  ]},
             ]},
            {"title": "Launch and sales", "description": "Marketing, listings, support readiness.",
             "discipline": "marketing",
             "stories": [
                 {"title": "Go-to-market", "discipline": "marketing",
                  "owner": "joseph", "estimate_hours": 20, "description": "Campaign, listings, support docs.",
                  "tasks": [
                      _t("Launch campaign assets", "marketing", "noel", 8),
                      _t("Marketplace listings live", "sales", "joseph", 6),
                      _t("Support FAQ and warranty doc", "support", "joseph", 6),
                  ]},
             ]},
        ],
        "dependencies": [
            {"blocker": "Final PCB revision and DFM check", "blocked": "Pilot batch of 50 boards"},
            {"blocker": "Freeze enclosure CAD", "blocked": "Packaging dieline and print"},
            {"blocker": "Pilot batch of 50 boards", "blocked": "Marketplace listings live"},
        ],
        "milestones": [
            {"name": "DFM sign-off", "offset_days": 10},
            {"name": "Pilot batch QC pass", "offset_days": 21},
            {"name": "Launch", "offset_days": 35},
        ],
    }


def _plan_listing(command):
    return {
        "summary": f"Decomposed: {command}",
        "department": "operations", "project": "Flipkart",
        "epics": [_listing_epic()],
        "dependencies": [
            {"blocker": "Product photography and renders", "blocked": "Publish marketplace listing"},
            {"blocker": "Listing copy and keywords", "blocked": "Publish marketplace listing"},
        ],
        "milestones": [{"name": "Listing live", "offset_days": 7}],
    }


# ------------------------------------------------------------ comment analysis

RISK_KEYWORDS = {
    "blocker": ["blocked", "blocker", "can't proceed", "cannot proceed", "stuck", "waiting on"],
    "risk": ["risk", "might slip", "delay", "behind schedule", "concern", "issue"],
    "dependency": ["depends on", "dependency", "needs", "after", "requires"],
    "urgent": ["urgent", "asap", "immediately", "critical", "today"],
}


def analyze_comment(body: str) -> list[str]:
    low = body.lower()
    return [flag for flag, kws in RISK_KEYWORDS.items() if any(k in low for k in kws)]
